#!/bin/bash

############################
# DDEV Commands Collection #
############################

## https://github.com/jackd248/ddev-commands-collection
## v0.3.1
## dcc-autogenerated
## <keep/>

#
# Overwrite the given config to your own needs
#
# default
composerPathApp="/var/www/html"
composerPathDeployment="/var/www/html"
deploymentPath="/var/www/html/.deployment"
logPathApp="/var/www/html/var/log/"
# sync
defaultSyncSystem="stage"
defaultSyncFileEnding="yaml"
# docker:deployment:update
dockerArtifactory="docker-os.artifactory.xima-services.de"
dockerImageDir="deployment"
dockerImageName=""
# copy-files
copyFilesPaths=(
  #"some/folder1/*|some/other/folder2/"
)
